sudo: true
language: cpp
compiler: gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install: sudo apt-get install -qq g++-5
addons: 
  apt: 
    packages: libboost-all-dev
#script: ./build.sh


#addons:
#  apt:
#    sources:
#    - boost-latest
#    - ubuntu-toolchain-r-test
#    packages:
#    - g++-4.9
#    #- libxerces-c-dev

#compiler:
#  - g++

#install:
#  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
#  - pip install cpp-coveralls --user `whoami`
#  - source ./travis/gtest.sh

#before_script:
#  - find / -type f -name 'gregorian.hpp'

script:
  - scons

#after_success:
#  - coveralls --gcov "gcov-4.9" --exclude test --exclude googletest --root . --build-root ".build/debug" --gcov-options '\-lp'
#  - find .build/debug -type f

#after_failure:
#  - cat ./.build/config.log